site_name: Lorello technical notes
theme: readthedocs
#site_url: 
repo_url: https://github.com/lorello/lorello.github.io/
site_description: "Unordered technical notes from LoreLLo"
site_author: "Lorenzo Salvadorini aka LoreLLo"
copyright: "It's all free, copy and use at your own risk"

theme: "readthedocs"
strict: true
remote_branch: "master"
